### ISSUE TITLE
CursorLine makes some Identifier invisible

### ISSUE THREAD

**Issue by eupiteco** [dylanaraps/wal.vim#12]
`:set cursorline` makes the Identifier elements to change it's color in the current line. Unfortunatly the new color matches the CursorLine `ctermbg` making it invisible.

Follows a screenshot to show what I mean.
![2018-09-03-211538_889x458_scrot](https://user-images.githubusercontent.com/972245/45003988-926c0580-afbe-11e8-8761-165e3f2a6b02.png)

**Comment by tott** [comment]
Running into the same issue. Did anyone find a good solution for this already?

**Comment by tott** [comment]
fwiw, i got good results just replacing the cursorline with
`hi CursorLine ctermbg=7 ctermfg=0`
and also
`hi CursorLineNr ctermbg=7 ctermfg=0`

**Comment by eupiteco** [comment]
@tott Thanks for the tip. I already tried that and it works.
But what if you want to keep the `CursorLine` color and change tha text one because it will look nicer?

**Comment by eupiteco** [comment]
@dylanaraps any updates on this or directions for me to try a fix?

**Comment by dylanaraps** [comment]
I need simple steps to reproduce this on my machine.

**Comment by eupiteco** [comment]
1. Set vim to use the wal colorscheme
2. `:set cursorline`
3. Open a HTML or any *ML tagsfile, the tags become invisible as you navigate to the lines they're on.

Since the tags have another color when not in the current line, an expected behavior would be it to keep the default color.

**Comment by ntk148v** [comment]
Hi all, i have the same issue.

![image](https://user-images.githubusercontent.com/10803803/57354436-a55e5780-7195-11e9-9112-3ee2370222be.png)

To workaround, I've changed `CursorLine` bg value to `2` instead. It looks better now :dancer: 

![image](https://user-images.githubusercontent.com/10803803/57354635-29b0da80-7196-11e9-91a4-405d9368a177.png)

I open a PR #16.
