### ISSUE TITLE
Missing Conceal highlights

### ISSUE THREAD

**Issue by qTipTip** [dylanaraps/wal.vim#18]
Hi! Cheers for a great plugin!

It seems to be missing the `Conceal` highlight-group, which may give undesirable results for people using the conceal-feature of vim.
I've circumvented this by setting the highlight-group to NONE.

```
hi Conceal ctermbg=NONE
```

**Comment by dylanaraps** [comment]
Fixed. :)

**Comment by qTipTip** [comment]
Cheers! :heart:
