### ISSUE TITLE
No bold/italics fonts

### ISSUE THREAD

**Issue by indeedwatson** [dylanaraps/wal.vim#2]
Whenever I have `colorscheme wal` enabled I don't see bold and italics when using for example markdown. However with the default colorscheme I can see them fine.

**Comment by dylanaraps** [comment]
Please update the colorscheme and let me know if it's fixed.

**Comment by indeedwatson** [comment]
I updated with vundle and it doesn't seem fixed. Is there anything you want me to do for more info?
