### ISSUE TITLE
Question about t_Co and termguicolors (neovim)

### ISSUE THREAD

**Issue by Kyle-Thompson** [dylanaraps/wal.vim#3]
I've been trying out this plugin and I've noticed something odd. Previously my init.vim set termguicolors and didn't set t_Co to anything. This worked fine for all the colorschemes I was using at the time. For this colorscheme though it seems like I need to "set t_Co=256" and remove the line that sets termguicolors. What's going on with this plugin to require that? I'm hoping I can find some middle ground between this colorscheme and others so that my settings (t_Co and termguicolors) don't have to change based only on my colorscheme.

**Comment by felipecustodio** [comment]
I had this issue too, I thought the plugin wasn't working, turns out I had to do the same as you and the colorscheme showed up. 

@dylanaraps maybe we should put this in the readme? :)

**Comment by dylanaraps** [comment]
I totally forgot about this issue. I apologise. 

I’ll add this to the wiki/README tomorrow.

**Comment by dylanaraps** [comment]
The reason `wal.vim` doesn't work in `termguicolors` mode is because `wal.vim` doesn't actually include the hex codes for colors. It just uses the terminal colors. When you set `termguicolors` you tell `neovim` to use the `guifg` and `guibg` which are unset in the colorscheme.
